# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14a5613bba09e88c4cf0af39cc7eb6c9caedb2cf2f63baa3ab55d00fa1d210b63aea284f6cc9727328bda953a58011fe7ffc4f4f5077b7e56cf5604ffab773fb

test:
  secret_key_base: 4785dcd279752c8890b60741750b84a76e5de6db20cefbb7d37b06ac197e125993de9c36af5a51c1fe4e953ce79004f1b717ff190911407cf9d1f09a7c344ef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
